### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theolampert** [briannadoubt/PocketBase#3]
Hi there, thanks for writing this, I'm looking into pocketbase for a project and might be able to contribute, It'd be great if there was a license file.

**Comment by briannadoubt** [comment]
Hey there! I'm about to push through a fairly big re-factor to this library. If you would like to push a relevant license file I would be more than happy to approve! We can definitely incorporate that into the re-worked concepts. Feel free to push up a PR :)

I've also created a long-running PR for v2 here: https://github.com/briannadoubt/PocketBase/pull/4

**Comment by briannadoubt** [comment]
I've added an MIT License
